# workflow name
name: Build and deploy docs

# main branch on push, auto run
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository main branch
        uses: actions/checkout@main

      - name: Setup Install Dependencies
        run: |
          npm set legacy-peer-deps=true
          npm install
      - name: Setup Deploy Private Key
        env:
          DOCS_DEPLOY_PRIVATE_KEY: ${{ secrets.DOCS_DEPLOY_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DOCS_DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Setup Git Infomation
        run: |
          git config --global user.name 'euris'
          git config --global user.email 'eurislee@gmail.com'
      - name: Deploy docs
        run: |
          npm run build:docs
          cd ./docs
          git init
          git add .
          git commit -am "Auto update at `date +'%Y-%m-%d %H:%M:%S'`"
          git branch -M docs
          git push --force --quiet "git@github.com:eurislee/starry_ui.git" docs:docs
